# Generated by Django 5.1.6 on 2025-03-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_locationdb_alter_categorydb_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdb',
            name='Location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
