# Generated by Django 5.1.6 on 2025-03-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobpostDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Image', models.ImageField(blank=True, null=True, upload_to='jobpost')),
                ('Job_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
                ('Job_Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Required_Skills', models.CharField(blank=True, max_length=100, null=True)),
                ('Education', models.CharField(blank=True, max_length=100, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Vacancy', models.IntegerField(blank=True, null=True)),
                ('Company_Details', models.TextField(blank=True, max_length=100, null=True)),
                ('Company_Website', models.CharField(blank=True, max_length=100, null=True)),
                ('Company_Email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
