# Generated by Django 5.1.6 on 2025-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField()),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=150, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('previous_company', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_role', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
