# Generated by Django 5.1.6 on 2025-03-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_jobapplicationdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicationdb',
            name='applied_at',
        ),
        migrations.AddField(
            model_name='jobapplicationdb',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Webapp.jobpostdb'),
        ),
    ]
