# Generated by Django 5.1.6 on 2025-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_remove_jobapplicationdb_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostdb',
            name='Salary',
        ),
        migrations.AddField(
            model_name='jobpostdb',
            name='Job_Salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
