# Generated by Django 5.1.6 on 2025-03-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_remove_jobpostdb_salary_jobpostdb_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostdb',
            name='Company_Details',
        ),
        migrations.RemoveField(
            model_name='jobpostdb',
            name='Company_Email',
        ),
        migrations.RemoveField(
            model_name='jobpostdb',
            name='Company_Website',
        ),
    ]
