# Generated by Django 5.1.6 on 2025-03-13 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_remove_jobpostdb_company_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostdb',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
