# Generated by Django 5.1.6 on 2025-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0009_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostdb',
            name='Education',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
