# Generated by Django 5.1.6 on 2025-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_alter_jobpostdb_education_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostdb',
            name='Education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostdb',
            name='Experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
