# Generated by Django 5.1.6 on 2025-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0011_alter_jobpostdb_education_alter_jobpostdb_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdb',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
