# Generated by Django 5.1.6 on 2025-03-15 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0012_jobapplicationdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdb',
            name='applied_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
